//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Athyl.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W")]
        public global::Microsoft.Xna.Framework.Input.Keys Up {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Up"]));
            }
            set {
                this["Up"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public global::Microsoft.Xna.Framework.Input.Keys Left {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Left"]));
            }
            set {
                this["Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public global::Microsoft.Xna.Framework.Input.Keys Down {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Down"]));
            }
            set {
                this["Down"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public global::Microsoft.Xna.Framework.Input.Keys Right {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Right"]));
            }
            set {
                this["Right"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("J")]
        public global::Microsoft.Xna.Framework.Input.Keys Shoot {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Shoot"]));
            }
            set {
                this["Shoot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("K")]
        public global::Microsoft.Xna.Framework.Input.Keys Jump {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Jump"]));
            }
            set {
                this["Jump"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LeftControl")]
        public global::Microsoft.Xna.Framework.Input.Keys Crouch {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Crouch"]));
            }
            set {
                this["Crouch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D1")]
        public global::Microsoft.Xna.Framework.Input.Keys Close {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Close"]));
            }
            set {
                this["Close"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D2")]
        public global::Microsoft.Xna.Framework.Input.Keys Middle {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Middle"]));
            }
            set {
                this["Middle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D3")]
        public global::Microsoft.Xna.Framework.Input.Keys Long {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Long"]));
            }
            set {
                this["Long"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E")]
        public global::Microsoft.Xna.Framework.Input.Keys Use {
            get {
                return ((global::Microsoft.Xna.Framework.Input.Keys)(this["Use"]));
            }
            set {
                this["Use"] = value;
            }
        }
    }
}
